name: Deploy Next.js to CloudPanel

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # 1. Masuk ke direktori project Anda di CloudPanel
            cd ~/htdocs/sertifikat.amania.id

            # 2. Load NVM (Wajib ada! Tanpa ini, SSH Github Actions tidak tahu perintah 'npm' itu apa)
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # 3. Sinkronisasi Git Paksa (Menghindari error git pull jika ada file terganti di server)
            git fetch --all
            git reset --hard origin/main

            # 4. Hapus cache lama Next.js (Agar UI benar-benar update 100% setelah build)
            rm -rf .next/cache

            # 5. Install ulang package & Build aplikasi
            npm install
            npm run build

            # 6. Restart Server Node.js
            # Perintah ini mencoba restart lewat PM2 (bawaan CloudPanel), 
            # jika PM2 tidak terdeteksi, ia akan mundur memakai pkill.
            pm2 restart all || pkill -u amania-sertifikat node || true