name: Deploy Next.js to CloudPanel

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # Variabel ini ditambahkan untuk menghilangkan warning Node.js 20
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/htdocs/sertifikat.amania.id
            git pull origin main
            npm install
            npm run build
            # Mematikan proses node lama milik user ini. CloudPanel akan otomatis menyalakannya ulang.
            # Tambahan "|| true" agar script tidak error jika kebetulan prosesnya memang sedang mati.
            pkill -u amania-sertifikat node || true